### PR TITLE
If a trait name is already carrying a FullStory type tag, don't mess with that.

### PR DESCRIPTION
**Pull request by fka3**
This allows users to specify that a quantity is "real" (i.e. float) even if the
momentary value happens to be an integer.  It also passes type mismatches
through so FullStory can complain about it, instead of assuming that the user
must have meant avg_purchase_real to be a string just 'cause they botched the
value when passing the trait in.  passed.  And that same avg_purchase_real won't
become avg_puchase_real_real, either, which is all good.

### CODE REVIEW

**Comment by fka3** [comment]
This is the second half of https://github.com/segment-integrations/analytics.js-integration-fullstory/pull/6

**Comment by hankim813** [comment]
this makes sense to me @f2prateek we do something similar for Salesforce, which requires `__c` attached at the end of the custom properties so we do a look up to see if the last three chars is `__c` and leave it if it is. 

Let's get this merged after #6 is sorted out. @fka3

**Comment by fka3** [comment]
Did you mean #6, which I closed already and split into #8 and #7?  Or did you mean #7?

They're independent enough that I can land them in either order; I have some actual heat under #7 because customers are encountering it in the wild.

**Comment by hankim813** [comment]
@fka3 sorry i meant #7 

@f2prateek can you comment on this?

**Comment by f2prateek** [comment]
I think we should update the PR to allow type tags for ones we can detect automatically (string, bool, date, etc.) and maybe just have this logic for numbers or types that can't be automatically detected if needed by the client.

The 2nd change (as @fka3 suggested) we'd want to make is to automatically look for our defined fields in spec and define the appropriate type tag.

**Comment by fka3** [comment]
I think you're misunderstanding the intent, really... if the user TELLS YOU WHAT THEY WANT, in this case by explicitly putting the admittedly odd (and therefore unlikely to be accidental) type tagging into their name, then I think this code should pass that name through unchanged, no matter what.  That's the big point.

Even if the user is "wrong" (maybe the say it's an int but they're passing a string, or vice versa), there are two possible errors: they might have mis-named the variable, or they may be making a mistake about the value passed.  If you always try to infer the type, you're assuming the second error is never being made (and you're going to make truly bizarre variable names, like foo_int_str, because you'll tack _str onto foo_int because a string was passed to it).  The fact that accepting the user's name ALSO lets them enforce foo_real even if the passed value happens to be integral is just a bonus you get from listening to what they said they wanted. 

Absent that, you're already doing a decent job of best-effort figuring what type to use if there is no indication from the user; I don't have any problem with that!

It would be a good idea to specify types for your defined fields that we don't recognize, but those will already be going through convert, so the obvious ones should already be tagged normally.  You did mention "total" as a spec'ed value (though I don't see it at https://segment.com/docs/spec/identify/#traits), so forcing that to total_real would probably be helpful, for example.

**Comment by f2prateek** [comment]
A customer using FullStory and Mixpanel will now have to see all their reports with `foo_real` in Mixpanel just because of FullStory to use `foo` as a real type.

And this only compounds if each integration had a limitation like this. **Imagine** if Mixpanel needed all floating numbers to be tagged `float`, and Amplitude needed them to be tagged `double`. Would our users send the same property 3 times tagged differently for each tool, adding extra properties to each event?

```js
analytics.track("Loaded a Page", {
  size_real: 32,
  size_double: 32,
  size_float: 32
});
```

Additionally, `size_double` would actually become `size_double_int` and `size_float_int` in FullStory.

To reiterate - your approach only makes sense if a customer is using only FullStory, which needs type tags instead of dynamically adapting types to incoming data as most tools try to do.

When a customer absolutely needs to force a type tag - they can call into FullStory directly using our `ready` API. It's more verbose, but the data in the end tools will be cleaner.

```js
analytics.track("Loaded a Page", { size: 32 }); // + pass a flag to ignore full story

analytics.ready(function(){
  // Whatever the equivalent call is.
  window.fs.track("Loaded a Page", { size_real: 32 });
});
```

**Comment by fka3** [comment]
I still feel like we're talking past each other here.  Would a phone call or VC help?

I'm not suggesting that everybody tag anything, nor that (hypothetically) MixPanel and FullStory have dueling type tags.  But if that world did develop, you'd fix it in these integration wrappers---FullStory would map all of { real, float, double } as _real, MixPanel's integration layer would map to float, etc.

But since I'm not suggesting that, that whole argument is a strawman anyway.

What I _am_ suggesting is that if the user _does_ offer FullStory style typing, for whatever reason (for example to make sure their real variables stay reals, even if the momentary value is integral), then that type tag should be respected, and that the integration layer shouldn't double it.  And yes, they pay for that by having MixPanel variables that have typed names, true.  It's harmless there and helpful here.

The `ready()` API is useful; I hadn't known about that.  But it's going to, in effect, force all users who care about any real-valued variable to use `analytics.ready()`, at least if they use FullStory... which is going to cramp use of your `analytics.identify()`, which I assume you'd like to avoid.

So, to me, the downside of _not_ doing this is that users either have to over-use `analytics.ready()`, or get doubled FullStory variables (`foo_real` and also `foo_int` once the numbers come up wrong).  And if they naively try to do it the FullStory way, they get truly bizarre variables (`foo_real_real` and `foo_real_int`)... which are basically permanent once set.

And the downside of _doing_ this... I honestly don't see it.  There's not an objection in principle, because you do something similar for Salesforce (and neither of you have decried that as a historical mistake).  There's not a burden on other tools, because you'd only get this behavior if you asked for it by using the type tags.  There's not a future multi-tool tug-of-war risk, really, because (a) the other tools don't ask for tagging anyway, and (b) if they did, this integration layer is a perfect place to resolve the tug-of-war for each tool individually.

You guys own the gate, obviously, and although you and @hankim813 seem to disagree, you're (plural) in your rights to just say no.  But I still don't understand the objection; I'll spot that FullStory's way is the oddball, but dealing with such variations is exactly why this layer should exist, and should handle it sensibly.

**Comment by f2prateek** [comment]
Given that I'm the only one against this, it's probably best to merge this :)

@fka3 sorry, but if you could rebase your changes against master we can get this out - if not I can get around to it sometime next week.

**Comment by fka3** [comment]
Done.

**Comment by fka3** [comment]
Thanks!

**Pull request merged**
