### PR TITLE
Add track event handler

### PR DESCRIPTION
**Pull request by sanjaybv**
### Overview
FullStory as a destination now supports ingestion of track event calls. This PR makes the following major changes to the integration code.
* Update the initialization snippet for adding the FullStory events API
* Add a handler for Segment's `track` API
* Add tests for the handler
* Add an `option` so that users can control if `track` events should be passed to FullStory.
* Remove type inferencing functionality and its related tests because it is not mandatory anymore to append the field names with their types. (like `_str`, `_int`, `_real`, etc.)
* Add the API source parameter for all the FullStory API calls, with relevant tests.

### `passEvents` option
The new option `passEvents` controls the behaviour of the passing `track` events to FullStory. (I was asked to describe the option in detail here, so that Segment's engineers can add it to the integration)

* `passEvents` is a boolean-type option which will be shown in the integration's settings page along with org and debug-mode fields. 
* This option can be mapped to the field name _"Pass track events to FullStory"_. 
* The detailed description can say _"Turning this setting on will send track events and properties to FullStory"_ and a hyperlink "Learn more" and link them to the documentation page `https://segment.com/docs/destinations/fullstory/`

If this setting is set to `true`, it will directly send the event name and properties to FullStory via the FullStory API; if set to `false`, it will skip the call entirely. All processing of the data received by the FullStory API, including cleaning and restructuring will be handled by FullStory client-side JS and server-side code.

FullStory events API is a new feature and we're beta testing it, so, we'd like to set this option to `false` by default. Once tested and this is out of the beta phase, we're planning to change the default behaviour of this option and set it `true` by default for the integration users.

~I'm in the process of updating the documentation at https://segment.com/docs/destinations/fullstory/; please let us know how you want this update. Is there a particular format? Who should I send it to?~

### CODE REVIEW

**Comment by chiplay** [comment]
@ccnixon I happened to notice that you're moving the integrations back into a mono repo: https://github.com/segmentio/analytics.js-integrations.  Would it be helpful for us to take our integration and this PR and move it over there?  If it's easier to wait until you're ready for it, no worries! We're just excited to start trying out custom events inside FullStory 😄 Thanks!

**Comment by jlee9595** [comment]
Hey @sanjaybv @chiplay thanks for your PR, I've just reviewed and it looks great. I will be moving this integration into our monorepo but it'll be easier if we merge the PR in this repo before doing that so I'll hold on moving till we merge this.

Everything looks good to me but I wanted to dig a little deeper into the `passEvents` setting. Historically we haven't supported settings for switching a single method like `track` on or off in an integration, as this is supported in some capacity today in [a more generalized fashion](https://segment.com/docs/sources/website/analytics.js/#selecting-destinations) in analytics.js. If it's a possibility for you guys I'd like to go forward without this option and have customers do it in the way outlined in that link.
However, I realize you guys want something that will be off by default and that will not be possible with that solution. If the 'off by default' behavior is something you guys need as part of the launch then we would be ok with adding the option temporarily during the beta phase as long as you guys can provide us with a concrete date when we can circle back and remove the option.
Sorry if this feels like a nitpick here but as context we've run into problems with integrations slowly accumulating an overwhelming amount of settings for small niches of functionality and this is something we're actively trying to curb today.

**Comment by sanjaybv** [comment]
@jlee9595 Hey. Thanks for reviewing the PR!

I had a chance to our team here about the `passEvents` setting. Yes, we only kind of needed that for beta testing the new `FS.event()` API feature. 

We totally understand that a lot of settings on that page can be overwhelming for a user and that it is better to have one standard way to deal with selecting destinations for API calls. So, we figured out a way to efficiently test this API by moving the settings control to our end. I believe we can go ahead without this setting and the `if` block in the code. I'll make the change to this PR soon.

**Comment by jlee9595** [comment]
That’s great to hear @sanjaybv , as soon as you can get that change in I’d be happy to merge the PR

**Comment by sanjaybv** [comment]
@jlee9595 Please check the latest commit. We're good to merge from our end.

**Review by jlee9595 — APPROVED** [review]

**Pull request merged**
